version: "3"
services:
  web:
    container_name: echo_app_1
    build: ./
    command: go run server.go
    volumes:
      - .:/echo_app
    ports:
      - "1234:1234"
    networks:
      - customnetwork
networks:
  customnetwork:
    driver: bridge
